### ISSUE TITLE
Security update needed

### ISSUE THREAD

**Issue by erip2** [harmyderoman/vuejs-confirm-dialog#35]
A security update is needed for "vue-template-compiler" package.

I have gotten this error:

vue-template-compiler vulnerable to client-side Cross-Site Scripting (XSS) #54

A vulnerability has been discovered in vue-template-compiler, that allows an attacker to perform XSS via prototype pollution. The attacker could change the prototype chain of some properties such as Object.prototype.staticClass or Object.prototype.staticStyle to execute arbitrary JavaScript code. Vue 2 has reached End-of-Life. This vulnerability has been patched in Vue 3.

**Comment by harmyderoman** [comment]
Thanks for highlighting the problem

**Comment by groenroos** [comment]
Running into this issue as well! Is there anything preventing an upgrade to `vue-template-compiler@3`?

**Comment by harmyderoman** [comment]
@groenroos 2.7.16 is latest

**Comment by groenroos** [comment]
Ah, right you are - the format of the Dependabot security alert misled me to believe that a fixed version exists:

<img width="933" alt="Screenshot 2024-08-07 at 02 06 35" src="https://github.com/user-attachments/assets/9618e27a-0021-4fb7-bf2b-06aefb91aeb1">

Since Vue 2 is EOL, is there an opportunity to drop this dependency? Or perhaps replace it with something else?

**Comment by harmyderoman** [comment]
@groenroos I'll check if I can can drop it

**Comment by kubica** [comment]
Same issue here :/ Is there already an update on this?

**Comment by harmyderoman** [comment]
@kubica An update is on the way

**Comment by harmyderoman** [comment]
Fixed #36
